# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *
from splib import *
import threading


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./data/res/about_cards.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        
        self.frame1()

        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        

    def frame1(self):
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_start = QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(430, 200, 70, 28))
        self.btn_start.setObjectName("btn_start")
        self.btn_team_manage = QPushButton(self.centralwidget)
        self.btn_team_manage.setGeometry(QtCore.QRect(300, 240, 200, 28))
        self.btn_team_manage.setObjectName("btn_team_manage")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 200, 120, 28))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)


        def getText():
            p = self.lineEdit.text()
            d = threading.Thread(target=battle, args=p)
            d.start()
        
        
        self.btn_start.clicked.connect(getText)
        
        self.btn_team_manage.clicked.connect(self.teamManage)
        self.retranslateUi(MainWindow)


    def teamManage(self):
        self.clearWidget()
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_view_team = QPushButton(self.centralwidget)
        self.btn_view_team.setGeometry(QtCore.QRect(300, 200, 200, 28))
        self.btn_view_team.setObjectName("btn_start")

        self.btn_add_team = QPushButton(self.centralwidget)
        self.btn_add_team.setGeometry(QtCore.QRect(300, 240, 200, 28))
        self.btn_add_team.setObjectName("btn_add_team")

        self.btn_delete_team = QPushButton(self.centralwidget)
        self.btn_delete_team.setGeometry(QtCore.QRect(300, 280, 200, 28))
        self.btn_delete_team.setObjectName("btn_delete_team")

        self.btn_back = QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(300, 320, 200, 28))
        self.btn_back.setObjectName("btn_back")

        MainWindow.setCentralWidget(self.centralwidget)

        def del_team():
            d = threading.Thread(target=delTeamGUI)
            d.start()

        def view_team():
            d = threading.Thread(target=viewTeam)
            d.start()
            d.join()

        def add_team():
            d = threading.Thread(target=addTeam)
            d.start()
            d.join()



        self.btn_view_team.clicked.connect(view_team)
        self.btn_add_team.clicked.connect(add_team)

        self.btn_delete_team.clicked.connect(del_team)
        self.btn_back.clicked.connect(self.frame1)

        
        self.retranslateUi2(MainWindow)


    def UiComponents(self):
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
  
        # creating a QListWidget
        #self.list_widget = QListWidget(self.centralwidget)


        self.list_widget = QListWidget(self.centralwidget)
        self.list_widget.setGeometry(QtCore.QRect(10, 10, 780, 500))
        self.list_widget.setObjectName("listWidget")
  
        # setting geometry to it
        #self.list_widget.setGeometry(50, 70, 150, 80)
  
        # list widget items
        item1 = QListWidgetItem("PyQt5 Geeks for Geeks")
        item2 = QListWidgetItem("B")
        item3 = QListWidgetItem("C")
        item4 = QListWidgetItem("D")
        item5 = QListWidgetItem("D")
        item6 = QListWidgetItem("D")
        item7 = QListWidgetItem("D")
        item8 = QListWidgetItem("D")
        item9 = QListWidgetItem("D")
        item10 = QListWidgetItem("D")
        item11 = QListWidgetItem("D")
  
        # adding items to the list widget
        self.list_widget.addItem(item1)
        self.list_widget.addItem(item2)
        self.list_widget.addItem(item3)
        self.list_widget.addItem(item4)
        self.list_widget.addItem(item5)
        self.list_widget.addItem(item6)
        self.list_widget.addItem(item7)
        self.list_widget.addItem(item8)
        self.list_widget.addItem(item9)
        self.list_widget.addItem(item10)
        self.list_widget.addItem(item11)
  
        # scroll bar
        self.scroll_bar = QScrollBar(self.centralwidget)
  
        # setting style sheet to the scroll bar
        self.scroll_bar.setStyleSheet("background : lightgreen;")
  
        # setting vertical scroll bar to it
        self.list_widget.setVerticalScrollBar(self.scroll_bar)
  
        # creating a label
        self.label = QLabel("GeesforGeeks")
  
        # setting geometry to the label
        self.label.setGeometry(230, 80, 280, 80)
  
        # making label multi line
        self.label.setWordWrap(True)
  
        # getting vertical scroll bar
        value = self.list_widget.verticalScrollBar()
  
        # setting text to the label
        self.label.setText("Vertical Scroll Bar : " + str(value))
        MainWindow.setCentralWidget(self.centralwidget)

        self.back_to_manage = QPushButton(self.centralwidget)
        self.back_to_manage.setGeometry(QtCore.QRect(580, 510, 93, 28))
        self.back_to_manage.setObjectName("back_to_manage")







    def clearWidget(self):
        self.btn_start.hide()
        self.btn_team_manage.hide()
        self.lineEdit.hide()




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Splib"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_team_manage.setText(_translate("MainWindow", "Team Manage"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Number of match"))

        


    def retranslateUi2(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btn_view_team.setText(_translate("MainWindow", "View Team"))
        self.btn_add_team.setText(_translate("MainWindow", "Add Team"))
        self.btn_delete_team.setText(_translate("MainWindow", "Delete Team"))
        self.btn_back.setText(_translate("MainWindow", "Back"))


        


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
